[package]
name = "bb_core"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
name = "bb_core"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
futures = "0.3.30"
js-sys = "0.3.68"
lazy_static = "1.4.0"
wasm-bindgen = "0.2.91"
wasm-bindgen-futures = "0.4.41"
