[package]
name = "bobbin-wasm-utils"
version = "0.1.0"
authors = ["Connor G Meehan <connorgm@pm.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
lyon = "1.0.1"
js-sys = { version = "0.3.64" }
owned_ttf_parser = { version = "0.19.0", features = ["opentype-layout"] }
thiserror = "1.0.49"
rustybuzz = "0.10.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
