[package]
name = "bb_vector_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Adds debug drawing via comfy, required to run the `testbed_*` examples.
# You'd never want to activate this in a real project but it's used internally for visual
# debugging.
debug_draw = ["comfy"]
# lyon_tessellation = ["lyon_tessellation"]

[dependencies]
glam = "0.24.2"

# Optional deps for the debug_draw feature.
comfy = { version = "0.2.0", optional = true }
thiserror = "1.0.51"
lyon_tessellation = "1.0.13"
lyon_path = "1.0.4"

[workspace]
members = [
    "examples/editor"
]
