[package]
name = "bb_vector_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Adds debug drawing via comfy, required to run the `testbed_*` examples.
# You'd never want to activate this in a real project but it's used internally for visual
# debugging.
debug_draw = ["dep:comfy", "dep:lyon_tessellation"]
lyon_path = ["dep:lyon_path"]

[dependencies]
glam = "0.24.2"
thiserror = "1.0.51"

# Optional deps for the debug_draw feature.
comfy = { version = "0.3.0", optional = true }
lyon_tessellation = { version = "1.0.13", optional = true }
# Optional deps for `lyon_path` feature
lyon_path = { version = "1.0.4", optional = true }

[workspace]
members = [
    "examples/editor",
    "examples/visualisations"
]
