[package]
name = "bevy_spts_vector_graphic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.13.0"
bevy_asset = "0.13.0"
bevy_ecs = "0.13.0"
bevy_hierarchy = "0.13.0"
bevy_math = "0.13.0"
bevy_reflect = "0.13.0"
bevy_render = "0.13.0"
bevy_transform = "0.13.0"
bevy_utils = "0.13.0"
lyon_path = "1.0.4"
lyon_tessellation = "1.0.13"
smallvec = "1.13.1"
