[package]
name = "visualisations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = "0.3.1"
bb_vector_network = { path = "../..", features = [ "debug_draw", "lyon_path" ] }
lyon_tessellation = "1.0.13"
lazy_static = "1.4.0"
glam = "0.25.0"
